//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace Telegram.Assets.Icons -Public -WinUIVersion 2.8 -InputFile Emulation.json
//       
//       Input file:
//           Emulation.json (5886 bytes created 7:46+02:00 Jul 15 2025)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ___________________________________________________________________________
// |       Object stats       | UAP v15 count | UAP v11 count | UAP v7 count |
// |__________________________|_______________|_______________|______________|
// | All CompositionObjects   |            46 |            52 |           48 |
// |--------------------------+---------------+---------------+--------------|
// | Expression animators     |             1 |             4 |            3 |
// | KeyFrame animators       |             4 |             4 |            3 |
// | Reference parameters     |             1 |             4 |            3 |
// | Expression operations    |             0 |             0 |            0 |
// |--------------------------+---------------+---------------+--------------|
// | Animated brushes         |             - |             - |            - |
// | Animated gradient stops  |             - |             - |            - |
// | ExpressionAnimations     |             1 |             1 |            1 |
// | PathKeyFrameAnimations   |             1 |             1 |            - |
// |--------------------------+---------------+---------------+--------------|
// | ContainerVisuals         |             1 |             1 |            1 |
// | ShapeVisuals             |             1 |             1 |            1 |
// |--------------------------+---------------+---------------+--------------|
// | ContainerShapes          |             1 |             1 |            1 |
// | CompositionSpriteShapes  |             3 |             3 |            3 |
// |--------------------------+---------------+---------------+--------------|
// | Brushes                  |             2 |             2 |            2 |
// | Gradient stops           |             3 |             3 |            3 |
// | CompositionVisualSurface |             - |             - |            - |
// ---------------------------------------------------------------------------
using Microsoft.Graphics.Canvas.Geometry;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.Graphics;
using Windows.UI;
using Windows.UI.Composition;

namespace Telegram.Assets.Icons
{
    // Name:        Capa 1/android compound
    // Frame rate:  60 fps
    // Frame count: 30
    // Duration:    500.0 mS
    public sealed class Emulation
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 0.500 seconds.
        internal const long c_durationTicks = 5000000;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            if (Emulation_AnimatedVisual_UAPv15.IsRuntimeCompatible())
            {
                var res = 
                    new Emulation_AnimatedVisual_UAPv15(
                        compositor
                        );
                    res.CreateAnimations();
                    return res;
            }

            if (Emulation_AnimatedVisual_UAPv11.IsRuntimeCompatible())
            {
                var res = 
                    new Emulation_AnimatedVisual_UAPv11(
                        compositor
                        );
                    res.CreateAnimations();
                    return res;
            }

            if (Emulation_AnimatedVisual_UAPv7.IsRuntimeCompatible())
            {
                var res = 
                    new Emulation_AnimatedVisual_UAPv7(
                        compositor
                        );
                    res.CreateAnimations();
                    return res;
            }

            return null;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 30d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(5000000);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 30d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "NormalToPointerOver_Start", 0.0 },
                { "NormalToPointerOver_End", 1 },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class Emulation_AnimatedVisual_UAPv15
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 5000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CanvasGeometry _geometry_5;
            CompositionColorBrush _colorBrush_AlmostSeaGreen_FF25A45B;
            CompositionContainerShape _containerShape;
            CompositionPath _path;
            CompositionPathGeometry _pathGeometry_2;
            CompositionSpriteShape _spriteShape_0;
            CompositionSpriteShape _spriteShape_1;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            PathKeyFrameAnimation CreatePathKeyFrameAnimation(float initialProgress, CompositionPath initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreatePathKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - - Shape tree root for layer: Main
            // - - ShapeGroup: left ear
            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(40.0149994F, 42.1010017F));
                    builder.AddLine(new Vector2(-11.9589996F, -44.5149994F));
                    builder.AddCubicBezier(new Vector2(-15.9449997F, -51.1819992F), new Vector2(-24.5620003F, -53.3149986F), new Vector2(-31.2150002F, -49.3289986F));
                    builder.AddCubicBezier(new Vector2(-37.8670006F, -45.3429985F), new Vector2(-40.0149994F, -36.7260017F), new Vector2(-36.0289993F, -30.073F));
                    builder.AddLine(new Vector2(14.0080004F, 53.3149986F));
                    builder.AddLine(new Vector2(40.0149994F, 42.1010017F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: Main
            // - - ShapeGroup: right ear
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-40.0149994F, 42.1010017F));
                    builder.AddLine(new Vector2(11.9589996F, -44.5149994F));
                    builder.AddCubicBezier(new Vector2(15.9449997F, -51.1819992F), new Vector2(24.5620003F, -53.3149986F), new Vector2(31.2150002F, -49.3289986F));
                    builder.AddCubicBezier(new Vector2(37.8670006F, -45.3429985F), new Vector2(40.0149994F, -36.7260017F), new Vector2(36.0289993F, -30.073F));
                    builder.AddLine(new Vector2(-14.0080004F, 53.3149986F));
                    builder.AddLine(new Vector2(-40.0149994F, 42.1010017F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_2()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_3(), Geometry_4(), Geometry_5() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-130.507004F, 12.4899998F));
                    builder.AddCubicBezier(new Vector2(-129.533997F, 0.150999993F), new Vector2(-119.537003F, -9.84700012F), new Vector2(-107.196999F, -10.8199997F));
                    builder.AddCubicBezier(new Vector2(-91.5110016F, -12.0570002F), new Vector2(-78.5179977F, 0.935000002F), new Vector2(-79.7549973F, 16.6210003F));
                    builder.AddCubicBezier(new Vector2(-80.7279968F, 28.9610004F), new Vector2(-90.7249985F, 38.9589996F), new Vector2(-103.065002F, 39.9319992F));
                    builder.AddCubicBezier(new Vector2(-103.759003F, 39.9860001F), new Vector2(-104.448997F, 40.0139999F), new Vector2(-105.130997F, 40.0139999F));
                    builder.AddCubicBezier(new Vector2(-119.874001F, 40.0149994F), new Vector2(-131.688995F, 27.4829998F), new Vector2(-130.507004F, 12.4899998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(79.7549973F, 12.4910002F));
                    builder.AddCubicBezier(new Vector2(80.7279968F, 0.150999993F), new Vector2(90.7249985F, -9.84700012F), new Vector2(103.065002F, -10.8199997F));
                    builder.AddCubicBezier(new Vector2(118.750999F, -12.0570002F), new Vector2(131.744003F, 0.935000002F), new Vector2(130.507004F, 16.6210003F));
                    builder.AddCubicBezier(new Vector2(129.533997F, 28.9619999F), new Vector2(119.537003F, 38.9589996F), new Vector2(107.196999F, 39.9319992F));
                    builder.AddCubicBezier(new Vector2(106.503998F, 39.9860001F), new Vector2(105.813004F, 40.0139999F), new Vector2(105.130997F, 40.0139999F));
                    builder.AddCubicBezier(new Vector2(90.387001F, 40.0159988F), new Vector2(78.5719986F, 27.4839993F), new Vector2(79.7549973F, 12.4910002F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_5()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-70.2720032F, -105.072998F));
                    builder.AddCubicBezier(new Vector2(-70.2720032F, -105.072998F), new Vector2(-96.2789993F, -93.8590012F), new Vector2(-96.2789993F, -93.8590012F));
                    builder.AddCubicBezier(new Vector2(-164.024994F, -58.8419991F), new Vector2(-224.557999F, 21.9750004F), new Vector2(-224.557999F, 103.362999F));
                    builder.AddCubicBezier(new Vector2(-224.557999F, 111.123001F), new Vector2(-218.270004F, 117.396004F), new Vector2(-210.522995F, 117.396004F));
                    builder.AddCubicBezier(new Vector2(-210.522995F, 117.396004F), new Vector2(210.522003F, 117.396004F), new Vector2(210.522003F, 117.396004F));
                    builder.AddCubicBezier(new Vector2(218.268997F, 117.396004F), new Vector2(224.557999F, 111.123001F), new Vector2(224.557999F, 103.362999F));
                    builder.AddCubicBezier(new Vector2(224.557999F, 21.9750004F), new Vector2(164.026001F, -58.8419991F), new Vector2(96.2789993F, -93.8590012F));
                    builder.AddCubicBezier(new Vector2(96.2789993F, -93.8590012F), new Vector2(70.2720032F, -105.072998F), new Vector2(70.2720032F, -105.072998F));
                    builder.AddCubicBezier(new Vector2(48.2519989F, -112.904999F), new Vector2(24.6730003F, -117.396004F), new Vector2(0F, -117.396004F));
                    builder.AddCubicBezier(new Vector2(-24.6730003F, -117.396004F), new Vector2(-48.2519989F, -112.904999F), new Vector2(-70.2720032F, -105.072998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = _geometry_5 = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Shape tree root for layer: Main
            // - - - ShapeGroup: kopf Offset:<224.808, 169.035>
            // - - left eye+right eye+head.PathGeometry
            // - Path
            CanvasGeometry Geometry_6()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_7(), Geometry_8(), Geometry_5() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            // - - - - - - Shape tree root for layer: Main
            // - - - - ShapeGroup: kopf Offset:<224.808, 169.035>
            // - - - left eye+right eye+head.PathGeometry
            // - - Path
            CanvasGeometry Geometry_7()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-130.511993F, 15.974F));
                    builder.AddCubicBezier(new Vector2(-130.438004F, 16.0119991F), new Vector2(-114.432999F, 16.0599995F), new Vector2(-104.417F, 16.0230007F));
                    builder.AddCubicBezier(new Vector2(-88.6200027F, 15.9639997F), new Vector2(-79.6190033F, 16.1520004F), new Vector2(-79.8160019F, 15.9960003F));
                    builder.AddCubicBezier(new Vector2(-79.7440033F, 16.1520004F), new Vector2(-90.8079987F, 15.9650002F), new Vector2(-103.003998F, 15.9949999F));
                    builder.AddCubicBezier(new Vector2(-103.699997F, 15.9969997F), new Vector2(-104.396004F, 15.9820004F), new Vector2(-105.078003F, 15.9820004F));
                    builder.AddCubicBezier(new Vector2(-119.820999F, 15.9829998F), new Vector2(-130.688004F, 16.1989994F), new Vector2(-130.511993F, 15.974F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - Shape tree root for layer: Main
            // - - - - ShapeGroup: kopf Offset:<224.808, 169.035>
            // - - - left eye+right eye+head.PathGeometry
            // - - Path
            CanvasGeometry Geometry_8()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(79.75F, 15.9750004F));
                    builder.AddCubicBezier(new Vector2(79.8119965F, 15.8240004F), new Vector2(93.5360031F, 15.9650002F), new Vector2(105.924004F, 15.9919996F));
                    builder.AddCubicBezier(new Vector2(121.658997F, 16.0270004F), new Vector2(130.380997F, 16.0900002F), new Vector2(130.445999F, 15.9969997F));
                    builder.AddCubicBezier(new Vector2(130.505997F, 16.0900002F), new Vector2(119.567001F, 15.9650002F), new Vector2(107.253998F, 15.9639997F));
                    builder.AddCubicBezier(new Vector2(106.558998F, 15.9639997F), new Vector2(105.866997F, 15.967F), new Vector2(105.184998F, 15.967F));
                    builder.AddCubicBezier(new Vector2(90.4410019F, 15.9689999F), new Vector2(79.8119965F, 16.0119991F), new Vector2(79.75F, 15.9750004F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostSeaGreen_FF25A45B()
            {
                return (_colorBrush_AlmostSeaGreen_FF25A45B == null)
                    ? _colorBrush_AlmostSeaGreen_FF25A45B = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x25, 0xA4, 0x5B))
                    : _colorBrush_AlmostSeaGreen_FF25A45B;
            }

            // - - - Shape tree root for layer: Main
            // - ShapeGroup: kopf Offset:<224.808, 169.035>
            // Stop 0
            CompositionColorGradientStop GradientStop_0_AlmostSeaGreen_FF24A45C()
            {
                return _c.CreateColorGradientStop(0F, Color.FromArgb(0xFF, 0x24, 0xA4, 0x5C));
            }

            // - - - Shape tree root for layer: Main
            // - ShapeGroup: kopf Offset:<224.808, 169.035>
            // Stop 1
            CompositionColorGradientStop GradientStop_0p35_AlmostMediumSeaGreen_FF2AC06D()
            {
                return _c.CreateColorGradientStop(0.349999994F, Color.FromArgb(0xFF, 0x2A, 0xC0, 0x6D));
            }

            // - - - Shape tree root for layer: Main
            // - ShapeGroup: kopf Offset:<224.808, 169.035>
            // Stop 2
            CompositionColorGradientStop GradientStop_1_AlmostMediumSeaGreen_FF2FDC80()
            {
                return _c.CreateColorGradientStop(1F, Color.FromArgb(0xFF, 0x2F, 0xDC, 0x80));
            }

            // Shape tree root for layer: Main
            CompositionContainerShape ContainerShape()
            {
                if (_containerShape != null) { return _containerShape; }
                var result = _containerShape = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(225F, 143.5F);
                var shapes = result.Shapes;
                // ShapeGroup: left ear
                shapes.Add(SpriteShape_0());
                // ShapeGroup: right ear
                shapes.Add(SpriteShape_1());
                // ShapeGroup: kopf Offset:<224.808, 169.035>
                shapes.Add(SpriteShape_2());
                return result;
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: kopf Offset:<224.808, 169.035>
            CompositionLinearGradientBrush LinearGradientBrush()
            {
                var result = _c.CreateLinearGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_AlmostSeaGreen_FF24A45C());
                colorStops.Add(GradientStop_0p35_AlmostMediumSeaGreen_FF2AC06D());
                colorStops.Add(GradientStop_1_AlmostMediumSeaGreen_FF2FDC80());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(0F, -118F);
                result.EndPoint = new Vector2(0F, 118F);
                return result;
            }

            CompositionPath Path()
            {
                if (_path != null) { return _path; }
                var result = _path = new CompositionPath(Geometry_2());
                return result;
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: left ear
            CompositionPathGeometry PathGeometry_0()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: right ear
            CompositionPathGeometry PathGeometry_1()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: kopf Offset:<224.808, 169.035>
            // left eye+right eye+head.PathGeometry
            CompositionPathGeometry PathGeometry_2()
            {
                if (_pathGeometry_2 != null) { return _pathGeometry_2; }
                var result = _pathGeometry_2 = _c.CreatePathGeometry();
                return result;
            }

            // - Shape tree root for layer: Main
            // Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                if (_spriteShape_0 != null) { return _spriteShape_0; }
                var result = _spriteShape_0 = _c.CreateSpriteShape(PathGeometry_0());
                result.FillBrush = ColorBrush_AlmostSeaGreen_FF25A45B();
                return result;
            }

            // - Shape tree root for layer: Main
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                if (_spriteShape_1 != null) { return _spriteShape_1; }
                var result = _spriteShape_1 = _c.CreateSpriteShape(PathGeometry_1());
                result.FillBrush = ColorBrush_AlmostSeaGreen_FF25A45B();
                return result;
            }

            // - Shape tree root for layer: Main
            // left eye+right eye+head
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<224.808, 169.035>
                var geometry = PathGeometry_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 224.807999F, 169.035004F), LinearGradientBrush());;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Shape tree root for layer: Main
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.0500000007F, 0F), new Vector2(0.899999976F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            // - - - Shape tree root for layer: Main
            // - ShapeGroup: kopf Offset:<224.808, 169.035>
            // left eye+right eye+head.PathGeometry
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_0()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path(), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.333333343F, Path(), HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(0.666666687F, new CompositionPath(Geometry_6()), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(1F, Path(), CubicBezierEasingFunction_0());
                return result;
            }

            // Shape tree root for layer: Main
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(450F, 287F);
                result.Shapes.Add(ContainerShape());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: left ear
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(100.774002F, 53.5649986F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.333333343F, new Vector2(100.774002F, 53.5649986F), HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(0.666666687F, new Vector2(141.524002F, 121.565002F), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(1F, new Vector2(100.774002F, 53.5649986F), CubicBezierEasingFunction_0());
                return result;
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: right ear
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(348.84201F, 53.5649986F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.333333343F, new Vector2(348.84201F, 53.5649986F), HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(0.666666687F, new Vector2(308.09201F, 121.565002F), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(1F, new Vector2(348.84201F, 53.5649986F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Shape tree root for layer: Main
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.850000024F, 0.850000024F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.333333343F, new Vector2(0.850000024F, 0.850000024F), HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(0.666666687F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(1F, new Vector2(0.850000024F, 0.850000024F), CubicBezierEasingFunction_0());
                return result;
            }

            internal Emulation_AnimatedVisual_UAPv15(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(450F, 287F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _containerShape.StartAnimation("Scale", ScaleVector2Animation(), AnimationController_0());
                _pathGeometry_2.StartAnimation("Path", PathKeyFrameAnimation_0(), AnimationController_0());
                _spriteShape_0.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_0());
                _spriteShape_1.StartAnimation("Offset", OffsetVector2Animation_1(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _containerShape.StopAnimation("Scale");
                _pathGeometry_2.StopAnimation("Path");
                _spriteShape_0.StopAnimation("Offset");
                _spriteShape_1.StopAnimation("Offset");
            }

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 15);
            }
        }

        sealed class Emulation_AnimatedVisual_UAPv11
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 5000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            CanvasGeometry _geometry_5;
            CompositionColorBrush _colorBrush_AlmostSeaGreen_FF25A45B;
            CompositionContainerShape _containerShape;
            CompositionPath _path;
            CompositionPathGeometry _pathGeometry_2;
            CompositionSpriteShape _spriteShape_0;
            CompositionSpriteShape _spriteShape_1;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            ExpressionAnimation _rootProgress;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            static void StartProgressBoundAnimation(
                CompositionObject target,
                string animatedPropertyName,
                CompositionAnimation animation,
                ExpressionAnimation controllerProgressExpression)
            {
                target.StartAnimation(animatedPropertyName, animation);
                var controller = target.TryGetAnimationController(animatedPropertyName);
                controller.Pause();
                controller.StartAnimation("Progress", controllerProgressExpression);
            }

            PathKeyFrameAnimation CreatePathKeyFrameAnimation(float initialProgress, CompositionPath initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreatePathKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            // - - - - Shape tree root for layer: Main
            // - - ShapeGroup: left ear
            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(40.0149994F, 42.1010017F));
                    builder.AddLine(new Vector2(-11.9589996F, -44.5149994F));
                    builder.AddCubicBezier(new Vector2(-15.9449997F, -51.1819992F), new Vector2(-24.5620003F, -53.3149986F), new Vector2(-31.2150002F, -49.3289986F));
                    builder.AddCubicBezier(new Vector2(-37.8670006F, -45.3429985F), new Vector2(-40.0149994F, -36.7260017F), new Vector2(-36.0289993F, -30.073F));
                    builder.AddLine(new Vector2(14.0080004F, 53.3149986F));
                    builder.AddLine(new Vector2(40.0149994F, 42.1010017F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: Main
            // - - ShapeGroup: right ear
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-40.0149994F, 42.1010017F));
                    builder.AddLine(new Vector2(11.9589996F, -44.5149994F));
                    builder.AddCubicBezier(new Vector2(15.9449997F, -51.1819992F), new Vector2(24.5620003F, -53.3149986F), new Vector2(31.2150002F, -49.3289986F));
                    builder.AddCubicBezier(new Vector2(37.8670006F, -45.3429985F), new Vector2(40.0149994F, -36.7260017F), new Vector2(36.0289993F, -30.073F));
                    builder.AddLine(new Vector2(-14.0080004F, 53.3149986F));
                    builder.AddLine(new Vector2(-40.0149994F, 42.1010017F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_2()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_3(), Geometry_4(), Geometry_5() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-130.507004F, 12.4899998F));
                    builder.AddCubicBezier(new Vector2(-129.533997F, 0.150999993F), new Vector2(-119.537003F, -9.84700012F), new Vector2(-107.196999F, -10.8199997F));
                    builder.AddCubicBezier(new Vector2(-91.5110016F, -12.0570002F), new Vector2(-78.5179977F, 0.935000002F), new Vector2(-79.7549973F, 16.6210003F));
                    builder.AddCubicBezier(new Vector2(-80.7279968F, 28.9610004F), new Vector2(-90.7249985F, 38.9589996F), new Vector2(-103.065002F, 39.9319992F));
                    builder.AddCubicBezier(new Vector2(-103.759003F, 39.9860001F), new Vector2(-104.448997F, 40.0139999F), new Vector2(-105.130997F, 40.0139999F));
                    builder.AddCubicBezier(new Vector2(-119.874001F, 40.0149994F), new Vector2(-131.688995F, 27.4829998F), new Vector2(-130.507004F, 12.4899998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(79.7549973F, 12.4910002F));
                    builder.AddCubicBezier(new Vector2(80.7279968F, 0.150999993F), new Vector2(90.7249985F, -9.84700012F), new Vector2(103.065002F, -10.8199997F));
                    builder.AddCubicBezier(new Vector2(118.750999F, -12.0570002F), new Vector2(131.744003F, 0.935000002F), new Vector2(130.507004F, 16.6210003F));
                    builder.AddCubicBezier(new Vector2(129.533997F, 28.9619999F), new Vector2(119.537003F, 38.9589996F), new Vector2(107.196999F, 39.9319992F));
                    builder.AddCubicBezier(new Vector2(106.503998F, 39.9860001F), new Vector2(105.813004F, 40.0139999F), new Vector2(105.130997F, 40.0139999F));
                    builder.AddCubicBezier(new Vector2(90.387001F, 40.0159988F), new Vector2(78.5719986F, 27.4839993F), new Vector2(79.7549973F, 12.4910002F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_5()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-70.2720032F, -105.072998F));
                    builder.AddCubicBezier(new Vector2(-70.2720032F, -105.072998F), new Vector2(-96.2789993F, -93.8590012F), new Vector2(-96.2789993F, -93.8590012F));
                    builder.AddCubicBezier(new Vector2(-164.024994F, -58.8419991F), new Vector2(-224.557999F, 21.9750004F), new Vector2(-224.557999F, 103.362999F));
                    builder.AddCubicBezier(new Vector2(-224.557999F, 111.123001F), new Vector2(-218.270004F, 117.396004F), new Vector2(-210.522995F, 117.396004F));
                    builder.AddCubicBezier(new Vector2(-210.522995F, 117.396004F), new Vector2(210.522003F, 117.396004F), new Vector2(210.522003F, 117.396004F));
                    builder.AddCubicBezier(new Vector2(218.268997F, 117.396004F), new Vector2(224.557999F, 111.123001F), new Vector2(224.557999F, 103.362999F));
                    builder.AddCubicBezier(new Vector2(224.557999F, 21.9750004F), new Vector2(164.026001F, -58.8419991F), new Vector2(96.2789993F, -93.8590012F));
                    builder.AddCubicBezier(new Vector2(96.2789993F, -93.8590012F), new Vector2(70.2720032F, -105.072998F), new Vector2(70.2720032F, -105.072998F));
                    builder.AddCubicBezier(new Vector2(48.2519989F, -112.904999F), new Vector2(24.6730003F, -117.396004F), new Vector2(0F, -117.396004F));
                    builder.AddCubicBezier(new Vector2(-24.6730003F, -117.396004F), new Vector2(-48.2519989F, -112.904999F), new Vector2(-70.2720032F, -105.072998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = _geometry_5 = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Shape tree root for layer: Main
            // - - - ShapeGroup: kopf Offset:<224.808, 169.035>
            // - - left eye+right eye+head.PathGeometry
            // - Path
            CanvasGeometry Geometry_6()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_7(), Geometry_8(), Geometry_5() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            // - - - - - - Shape tree root for layer: Main
            // - - - - ShapeGroup: kopf Offset:<224.808, 169.035>
            // - - - left eye+right eye+head.PathGeometry
            // - - Path
            CanvasGeometry Geometry_7()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-130.511993F, 15.974F));
                    builder.AddCubicBezier(new Vector2(-130.438004F, 16.0119991F), new Vector2(-114.432999F, 16.0599995F), new Vector2(-104.417F, 16.0230007F));
                    builder.AddCubicBezier(new Vector2(-88.6200027F, 15.9639997F), new Vector2(-79.6190033F, 16.1520004F), new Vector2(-79.8160019F, 15.9960003F));
                    builder.AddCubicBezier(new Vector2(-79.7440033F, 16.1520004F), new Vector2(-90.8079987F, 15.9650002F), new Vector2(-103.003998F, 15.9949999F));
                    builder.AddCubicBezier(new Vector2(-103.699997F, 15.9969997F), new Vector2(-104.396004F, 15.9820004F), new Vector2(-105.078003F, 15.9820004F));
                    builder.AddCubicBezier(new Vector2(-119.820999F, 15.9829998F), new Vector2(-130.688004F, 16.1989994F), new Vector2(-130.511993F, 15.974F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - - Shape tree root for layer: Main
            // - - - - ShapeGroup: kopf Offset:<224.808, 169.035>
            // - - - left eye+right eye+head.PathGeometry
            // - - Path
            CanvasGeometry Geometry_8()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(79.75F, 15.9750004F));
                    builder.AddCubicBezier(new Vector2(79.8119965F, 15.8240004F), new Vector2(93.5360031F, 15.9650002F), new Vector2(105.924004F, 15.9919996F));
                    builder.AddCubicBezier(new Vector2(121.658997F, 16.0270004F), new Vector2(130.380997F, 16.0900002F), new Vector2(130.445999F, 15.9969997F));
                    builder.AddCubicBezier(new Vector2(130.505997F, 16.0900002F), new Vector2(119.567001F, 15.9650002F), new Vector2(107.253998F, 15.9639997F));
                    builder.AddCubicBezier(new Vector2(106.558998F, 15.9639997F), new Vector2(105.866997F, 15.967F), new Vector2(105.184998F, 15.967F));
                    builder.AddCubicBezier(new Vector2(90.4410019F, 15.9689999F), new Vector2(79.8119965F, 16.0119991F), new Vector2(79.75F, 15.9750004F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostSeaGreen_FF25A45B()
            {
                return (_colorBrush_AlmostSeaGreen_FF25A45B == null)
                    ? _colorBrush_AlmostSeaGreen_FF25A45B = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x25, 0xA4, 0x5B))
                    : _colorBrush_AlmostSeaGreen_FF25A45B;
            }

            // - - - Shape tree root for layer: Main
            // - ShapeGroup: kopf Offset:<224.808, 169.035>
            // Stop 0
            CompositionColorGradientStop GradientStop_0_AlmostSeaGreen_FF24A45C()
            {
                return _c.CreateColorGradientStop(0F, Color.FromArgb(0xFF, 0x24, 0xA4, 0x5C));
            }

            // - - - Shape tree root for layer: Main
            // - ShapeGroup: kopf Offset:<224.808, 169.035>
            // Stop 1
            CompositionColorGradientStop GradientStop_0p35_AlmostMediumSeaGreen_FF2AC06D()
            {
                return _c.CreateColorGradientStop(0.349999994F, Color.FromArgb(0xFF, 0x2A, 0xC0, 0x6D));
            }

            // - - - Shape tree root for layer: Main
            // - ShapeGroup: kopf Offset:<224.808, 169.035>
            // Stop 2
            CompositionColorGradientStop GradientStop_1_AlmostMediumSeaGreen_FF2FDC80()
            {
                return _c.CreateColorGradientStop(1F, Color.FromArgb(0xFF, 0x2F, 0xDC, 0x80));
            }

            // Shape tree root for layer: Main
            CompositionContainerShape ContainerShape()
            {
                if (_containerShape != null) { return _containerShape; }
                var result = _containerShape = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(225F, 143.5F);
                var shapes = result.Shapes;
                // ShapeGroup: left ear
                shapes.Add(SpriteShape_0());
                // ShapeGroup: right ear
                shapes.Add(SpriteShape_1());
                // ShapeGroup: kopf Offset:<224.808, 169.035>
                shapes.Add(SpriteShape_2());
                return result;
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: kopf Offset:<224.808, 169.035>
            CompositionLinearGradientBrush LinearGradientBrush()
            {
                var result = _c.CreateLinearGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_AlmostSeaGreen_FF24A45C());
                colorStops.Add(GradientStop_0p35_AlmostMediumSeaGreen_FF2AC06D());
                colorStops.Add(GradientStop_1_AlmostMediumSeaGreen_FF2FDC80());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(0F, -118F);
                result.EndPoint = new Vector2(0F, 118F);
                return result;
            }

            CompositionPath Path()
            {
                if (_path != null) { return _path; }
                var result = _path = new CompositionPath(Geometry_2());
                return result;
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: left ear
            CompositionPathGeometry PathGeometry_0()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: right ear
            CompositionPathGeometry PathGeometry_1()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: kopf Offset:<224.808, 169.035>
            // left eye+right eye+head.PathGeometry
            CompositionPathGeometry PathGeometry_2()
            {
                if (_pathGeometry_2 != null) { return _pathGeometry_2; }
                var result = _pathGeometry_2 = _c.CreatePathGeometry();
                return result;
            }

            // - Shape tree root for layer: Main
            // Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                if (_spriteShape_0 != null) { return _spriteShape_0; }
                var result = _spriteShape_0 = _c.CreateSpriteShape(PathGeometry_0());
                result.FillBrush = ColorBrush_AlmostSeaGreen_FF25A45B();
                return result;
            }

            // - Shape tree root for layer: Main
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                if (_spriteShape_1 != null) { return _spriteShape_1; }
                var result = _spriteShape_1 = _c.CreateSpriteShape(PathGeometry_1());
                result.FillBrush = ColorBrush_AlmostSeaGreen_FF25A45B();
                return result;
            }

            // - Shape tree root for layer: Main
            // left eye+right eye+head
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<224.808, 169.035>
                var geometry = PathGeometry_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 224.807999F, 169.035004F), LinearGradientBrush());;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Shape tree root for layer: Main
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.0500000007F, 0F), new Vector2(0.899999976F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            ExpressionAnimation RootProgress()
            {
                if (_rootProgress != null) { return _rootProgress; }
                var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            // - - - Shape tree root for layer: Main
            // - ShapeGroup: kopf Offset:<224.808, 169.035>
            // left eye+right eye+head.PathGeometry
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_0()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path(), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.333333343F, Path(), HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(0.666666687F, new CompositionPath(Geometry_6()), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(1F, Path(), CubicBezierEasingFunction_0());
                return result;
            }

            // Shape tree root for layer: Main
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(450F, 287F);
                result.Shapes.Add(ContainerShape());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: left ear
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(100.774002F, 53.5649986F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.333333343F, new Vector2(100.774002F, 53.5649986F), HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(0.666666687F, new Vector2(141.524002F, 121.565002F), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(1F, new Vector2(100.774002F, 53.5649986F), CubicBezierEasingFunction_0());
                return result;
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: right ear
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(348.84201F, 53.5649986F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.333333343F, new Vector2(348.84201F, 53.5649986F), HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(0.666666687F, new Vector2(308.09201F, 121.565002F), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(1F, new Vector2(348.84201F, 53.5649986F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Shape tree root for layer: Main
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.850000024F, 0.850000024F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.333333343F, new Vector2(0.850000024F, 0.850000024F), HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(0.666666687F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(1F, new Vector2(0.850000024F, 0.850000024F), CubicBezierEasingFunction_0());
                return result;
            }

            internal Emulation_AnimatedVisual_UAPv11(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(450F, 287F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                StartProgressBoundAnimation(_containerShape, "Scale", ScaleVector2Animation(), RootProgress());
                StartProgressBoundAnimation(_pathGeometry_2, "Path", PathKeyFrameAnimation_0(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_0, "Offset", OffsetVector2Animation_0(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_1, "Offset", OffsetVector2Animation_1(), RootProgress());
            }

            public void DestroyAnimations()
            {
                _containerShape.StopAnimation("Scale");
                _pathGeometry_2.StopAnimation("Path");
                _spriteShape_0.StopAnimation("Offset");
                _spriteShape_1.StopAnimation("Offset");
            }

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 11);
            }
        }

        sealed class Emulation_AnimatedVisual_UAPv7
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 5000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            CompositionColorBrush _colorBrush_AlmostSeaGreen_FF25A45B;
            CompositionContainerShape _containerShape;
            CompositionSpriteShape _spriteShape_0;
            CompositionSpriteShape _spriteShape_1;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            ExpressionAnimation _rootProgress;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            static void StartProgressBoundAnimation(
                CompositionObject target,
                string animatedPropertyName,
                CompositionAnimation animation,
                ExpressionAnimation controllerProgressExpression)
            {
                target.StartAnimation(animatedPropertyName, animation);
                var controller = target.TryGetAnimationController(animatedPropertyName);
                controller.Pause();
                controller.StartAnimation("Progress", controllerProgressExpression);
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            // - - - - Shape tree root for layer: Main
            // - - ShapeGroup: left ear
            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(40.0149994F, 42.1010017F));
                    builder.AddLine(new Vector2(-11.9589996F, -44.5149994F));
                    builder.AddCubicBezier(new Vector2(-15.9449997F, -51.1819992F), new Vector2(-24.5620003F, -53.3149986F), new Vector2(-31.2150002F, -49.3289986F));
                    builder.AddCubicBezier(new Vector2(-37.8670006F, -45.3429985F), new Vector2(-40.0149994F, -36.7260017F), new Vector2(-36.0289993F, -30.073F));
                    builder.AddLine(new Vector2(14.0080004F, 53.3149986F));
                    builder.AddLine(new Vector2(40.0149994F, 42.1010017F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: Main
            // - - ShapeGroup: right ear
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-40.0149994F, 42.1010017F));
                    builder.AddLine(new Vector2(11.9589996F, -44.5149994F));
                    builder.AddCubicBezier(new Vector2(15.9449997F, -51.1819992F), new Vector2(24.5620003F, -53.3149986F), new Vector2(31.2150002F, -49.3289986F));
                    builder.AddCubicBezier(new Vector2(37.8670006F, -45.3429985F), new Vector2(40.0149994F, -36.7260017F), new Vector2(36.0289993F, -30.073F));
                    builder.AddLine(new Vector2(-14.0080004F, 53.3149986F));
                    builder.AddLine(new Vector2(-40.0149994F, 42.1010017F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: Main
            // - - ShapeGroup: kopf Offset:<224.808, 169.035>
            // - left eye+right eye+head.PathGeometry
            CanvasGeometry Geometry_2()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_3(), Geometry_4(), Geometry_5() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            // - - - - - Shape tree root for layer: Main
            // - - - ShapeGroup: kopf Offset:<224.808, 169.035>
            // - - left eye+right eye+head.PathGeometry
            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-130.507004F, 12.4899998F));
                    builder.AddCubicBezier(new Vector2(-129.533997F, 0.150999993F), new Vector2(-119.537003F, -9.84700012F), new Vector2(-107.196999F, -10.8199997F));
                    builder.AddCubicBezier(new Vector2(-91.5110016F, -12.0570002F), new Vector2(-78.5179977F, 0.935000002F), new Vector2(-79.7549973F, 16.6210003F));
                    builder.AddCubicBezier(new Vector2(-80.7279968F, 28.9610004F), new Vector2(-90.7249985F, 38.9589996F), new Vector2(-103.065002F, 39.9319992F));
                    builder.AddCubicBezier(new Vector2(-103.759003F, 39.9860001F), new Vector2(-104.448997F, 40.0139999F), new Vector2(-105.130997F, 40.0139999F));
                    builder.AddCubicBezier(new Vector2(-119.874001F, 40.0149994F), new Vector2(-131.688995F, 27.4829998F), new Vector2(-130.507004F, 12.4899998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Shape tree root for layer: Main
            // - - - ShapeGroup: kopf Offset:<224.808, 169.035>
            // - - left eye+right eye+head.PathGeometry
            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(79.7549973F, 12.4910002F));
                    builder.AddCubicBezier(new Vector2(80.7279968F, 0.150999993F), new Vector2(90.7249985F, -9.84700012F), new Vector2(103.065002F, -10.8199997F));
                    builder.AddCubicBezier(new Vector2(118.750999F, -12.0570002F), new Vector2(131.744003F, 0.935000002F), new Vector2(130.507004F, 16.6210003F));
                    builder.AddCubicBezier(new Vector2(129.533997F, 28.9619999F), new Vector2(119.537003F, 38.9589996F), new Vector2(107.196999F, 39.9319992F));
                    builder.AddCubicBezier(new Vector2(106.503998F, 39.9860001F), new Vector2(105.813004F, 40.0139999F), new Vector2(105.130997F, 40.0139999F));
                    builder.AddCubicBezier(new Vector2(90.387001F, 40.0159988F), new Vector2(78.5719986F, 27.4839993F), new Vector2(79.7549973F, 12.4910002F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Shape tree root for layer: Main
            // - - - ShapeGroup: kopf Offset:<224.808, 169.035>
            // - - left eye+right eye+head.PathGeometry
            CanvasGeometry Geometry_5()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-70.2720032F, -105.072998F));
                    builder.AddLine(new Vector2(-96.2789993F, -93.8590012F));
                    builder.AddCubicBezier(new Vector2(-164.024994F, -58.8419991F), new Vector2(-224.557999F, 21.9750004F), new Vector2(-224.557999F, 103.362999F));
                    builder.AddCubicBezier(new Vector2(-224.557999F, 111.123001F), new Vector2(-218.270004F, 117.396004F), new Vector2(-210.522995F, 117.396004F));
                    builder.AddLine(new Vector2(210.522003F, 117.396004F));
                    builder.AddCubicBezier(new Vector2(218.268997F, 117.396004F), new Vector2(224.557999F, 111.123001F), new Vector2(224.557999F, 103.362999F));
                    builder.AddCubicBezier(new Vector2(224.557999F, 21.9750004F), new Vector2(164.026001F, -58.8419991F), new Vector2(96.2789993F, -93.8590012F));
                    builder.AddLine(new Vector2(70.2720032F, -105.072998F));
                    builder.AddCubicBezier(new Vector2(48.2519989F, -112.904999F), new Vector2(24.6730003F, -117.396004F), new Vector2(0F, -117.396004F));
                    builder.AddCubicBezier(new Vector2(-24.6730003F, -117.396004F), new Vector2(-48.2519989F, -112.904999F), new Vector2(-70.2720032F, -105.072998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostSeaGreen_FF25A45B()
            {
                return (_colorBrush_AlmostSeaGreen_FF25A45B == null)
                    ? _colorBrush_AlmostSeaGreen_FF25A45B = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x25, 0xA4, 0x5B))
                    : _colorBrush_AlmostSeaGreen_FF25A45B;
            }

            // - - - Shape tree root for layer: Main
            // - ShapeGroup: kopf Offset:<224.808, 169.035>
            // Stop 0
            CompositionColorGradientStop GradientStop_0_AlmostSeaGreen_FF24A45C()
            {
                return _c.CreateColorGradientStop(0F, Color.FromArgb(0xFF, 0x24, 0xA4, 0x5C));
            }

            // - - - Shape tree root for layer: Main
            // - ShapeGroup: kopf Offset:<224.808, 169.035>
            // Stop 1
            CompositionColorGradientStop GradientStop_0p35_AlmostMediumSeaGreen_FF2AC06D()
            {
                return _c.CreateColorGradientStop(0.349999994F, Color.FromArgb(0xFF, 0x2A, 0xC0, 0x6D));
            }

            // - - - Shape tree root for layer: Main
            // - ShapeGroup: kopf Offset:<224.808, 169.035>
            // Stop 2
            CompositionColorGradientStop GradientStop_1_AlmostMediumSeaGreen_FF2FDC80()
            {
                return _c.CreateColorGradientStop(1F, Color.FromArgb(0xFF, 0x2F, 0xDC, 0x80));
            }

            // Shape tree root for layer: Main
            CompositionContainerShape ContainerShape()
            {
                if (_containerShape != null) { return _containerShape; }
                var result = _containerShape = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(225F, 143.5F);
                var shapes = result.Shapes;
                // ShapeGroup: left ear
                shapes.Add(SpriteShape_0());
                // ShapeGroup: right ear
                shapes.Add(SpriteShape_1());
                // ShapeGroup: kopf Offset:<224.808, 169.035>
                shapes.Add(SpriteShape_2());
                return result;
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: kopf Offset:<224.808, 169.035>
            CompositionLinearGradientBrush LinearGradientBrush()
            {
                var result = _c.CreateLinearGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_AlmostSeaGreen_FF24A45C());
                colorStops.Add(GradientStop_0p35_AlmostMediumSeaGreen_FF2AC06D());
                colorStops.Add(GradientStop_1_AlmostMediumSeaGreen_FF2FDC80());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(0F, -118F);
                result.EndPoint = new Vector2(0F, 118F);
                return result;
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: left ear
            CompositionPathGeometry PathGeometry_0()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: right ear
            CompositionPathGeometry PathGeometry_1()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: kopf Offset:<224.808, 169.035>
            // left eye+right eye+head.PathGeometry
            CompositionPathGeometry PathGeometry_2()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_2()));
            }

            // - Shape tree root for layer: Main
            // Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                if (_spriteShape_0 != null) { return _spriteShape_0; }
                var result = _spriteShape_0 = _c.CreateSpriteShape(PathGeometry_0());
                result.FillBrush = ColorBrush_AlmostSeaGreen_FF25A45B();
                return result;
            }

            // - Shape tree root for layer: Main
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                if (_spriteShape_1 != null) { return _spriteShape_1; }
                var result = _spriteShape_1 = _c.CreateSpriteShape(PathGeometry_1());
                result.FillBrush = ColorBrush_AlmostSeaGreen_FF25A45B();
                return result;
            }

            // - Shape tree root for layer: Main
            // left eye+right eye+head
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<224.808, 169.035>
                var geometry = PathGeometry_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 224.807999F, 169.035004F), LinearGradientBrush());;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Shape tree root for layer: Main
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.0500000007F, 0F), new Vector2(0.899999976F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            ExpressionAnimation RootProgress()
            {
                if (_rootProgress != null) { return _rootProgress; }
                var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            // Shape tree root for layer: Main
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(450F, 287F);
                result.Shapes.Add(ContainerShape());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: left ear
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(100.774002F, 53.5649986F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.333333343F, new Vector2(100.774002F, 53.5649986F), HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(0.666666687F, new Vector2(141.524002F, 121.565002F), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(1F, new Vector2(100.774002F, 53.5649986F), CubicBezierEasingFunction_0());
                return result;
            }

            // - - Shape tree root for layer: Main
            // ShapeGroup: right ear
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(348.84201F, 53.5649986F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.333333343F, new Vector2(348.84201F, 53.5649986F), HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(0.666666687F, new Vector2(308.09201F, 121.565002F), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(1F, new Vector2(348.84201F, 53.5649986F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Shape tree root for layer: Main
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.850000024F, 0.850000024F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.333333343F, new Vector2(0.850000024F, 0.850000024F), HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(0.666666687F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(1F, new Vector2(0.850000024F, 0.850000024F), CubicBezierEasingFunction_0());
                return result;
            }

            internal Emulation_AnimatedVisual_UAPv7(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(450F, 287F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                StartProgressBoundAnimation(_containerShape, "Scale", ScaleVector2Animation(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_0, "Offset", OffsetVector2Animation_0(), RootProgress());
                StartProgressBoundAnimation(_spriteShape_1, "Offset", OffsetVector2Animation_1(), RootProgress());
            }

            public void DestroyAnimations()
            {
                _containerShape.StopAnimation("Scale");
                _spriteShape_0.StopAnimation("Offset");
                _spriteShape_1.StopAnimation("Offset");
            }

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 7);
            }
        }
    }
}
